name: jupysql-doc

channels:
  - conda-forge


dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - pip
  - pip:
    - jupyter-book
    # duckdb example
    - duckdb==0.7.0
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    - pkgmt>=0.1.7
    - -e ..